language: php
php:
  - 7.0
  - 7.1
install: 
  - composer install --no-interaction --prefer-source
before_script:
  - composer require codacy/coverage --dev
script:
  - bin/all-checks
after_script:
  - php vendor/bin/codacycoverage phpunit

  